### ISSUE TITLE
javax.naming.directory.InitialDirContext is a restricted class

### ISSUE THREAD

**Issue by thelong1EU** [carlosCharz/fcmxmppserverv2#5]
I keep getting this error, but only when I deploy to server. When I run the main function all works well:

```
java.lang.NoClassDefFoundError: javax.naming.directory.InitialDirContext is a restricted class. Please see the Google  App Engine developer's guide for more details.
	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:50)
	at org.jivesoftware.smack.util.dns.javax.JavaxResolver.<clinit>(JavaxResolver.java:50)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jivesoftware.smack.SmackInitialization.loadSmackClass(SmackInitialization.java:213)
	at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(SmackInitialization.java:193)
	at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:163)
	at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:148)
	at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:116)
	at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96)
	at org.jivesoftware.smack.provider.ProviderManager.<clinit>(ProviderManager.java:121)
	at eu.long1.jwnotes.backend.server.CcsClient.<init>(CcsClient.java:62)
	at eu.long1.jwnotes.backend.server.CcsClient.<init>(CcsClient.java:53)
	at eu.long1.jwnotes.backend.server.CcsClient.prepareClient(CcsClient.java:83)
	at eu.long1.jwnotes.backend.server.GCMContextListener.contextInitialized(GCMContextListener.java:26)
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:548)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:268)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:262)
	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:45)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:217)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:215)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:215)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:349)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:222)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by carlosCharz** [comment]
The app was intended to be a simple java app. If you want to adapt to be deployed in a server you should take into consideration the architecture selected. Example: web.xml, servlets, tomcat, etc.  Make sure that the connection is closed when you undeploy as well.

**Comment by thelong1EU** [comment]
I think I get it working using the 3.2.1 version
